#!/bin/bash

me=${BASH_SOURCE[0]}
here=$(realpath $(dirname $me))
lib=$(realpath $here/../lib)
export PYTHONPATH=${lib}:$PYTHONPATH

if [ -z "$PYTHON" ]; then
    PYTHON=python2.7
fi

b=$(basename $PYTHON)
m=$(basename $me)

if [ -z "$PROFILE" ]; then
    PROF_ARGS=""
else
    PROF_ARGS="-m cProfile -o $m.$b.prof "
fi

exec $PYTHON $PROF_ARGS ${me}.py "$@"
