#!/bin/bash

me=${BASH_SOURCE[0]}
here=$(realpath $(dirname $me))
lib=$(realpath $here/../lib)
export PYTHONPATH=${lib}:$PYTHONPATH

if [ -z "$PYTHON" ]; then
    $PYTHON=python2.7
fi

exec $PYTHON ${me}.py "$@"
